name: HandMesh

channels:
  - libboost-dev
  - defaults
dependencies:
  - pip
  - python=3.6.13
  - pip:
    - numpy==1.19.1
    - scipy==1.4.1
    - matplotlib==3.3.2
    - opencv-python==4.4.0.46
    - scikit-learn
    - scikit-image==0.16.2
    - termcolor
    - torch_geometric
    - git+https://github.com/MPI-IS/mesh.git
    - chumpy
    - torch-scatter==2.0.7
    - torch-sparse==0.6.9
    - cmake
    - torchvision==0.8.2 
    - transforms3d 
    - pycocotools 
    - smplpytorch
    - ipykernel
    - tensorboardX
    - open3d
